/* eslint-disable */
// Auto-generated by scripts/embed-combined.mjs - do not edit manually.
// Combined data is embedded so it is available after publish.

export const EMBEDDED_COMBINED_XLSX_BASE64: string = "";
